### ISSUE TITLE
No peer certificate

### ISSUE THREAD

**Issue by natarajnattu** [Medisana/Android-Standalone#1]
We've been testing the app for a few hours.. we changed the productions keys to test server keys... and something halting application while converting the exchange key... can anyone pl eloberate this..

thx...  

this is the error log

04-20 20:12:40.152    2559-2574/com.example.miguel.myapplication W/EGL_emulation﹕ eglSurfaceAttrib not implemented
04-20 20:12:40.152    2559-2574/com.example.miguel.myapplication W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5bab8a0, error=EGL_SUCCESS
04-20 20:12:40.199    2559-2574/com.example.miguel.myapplication W/EGL_emulation﹕ eglSurfaceAttrib not implemented
04-20 20:12:40.199    2559-2574/com.example.miguel.myapplication W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6641600, error=EGL_SUCCESS
04-20 20:12:40.433    2559-2577/com.example.miguel.myapplication W/System.err﹕ javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
04-20 20:12:40.433    2559-2577/com.example.miguel.myapplication W/System.err﹕ at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
04-20 20:12:40.433    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
04-20 20:12:40.433    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at com.example.miguel.myapplication.service.servercommunication.ExangeToken.exangeToken(ExangeToken.java:60)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at com.example.miguel.myapplication.activity.asynctask.ExchangeTokenActivity$ExchangeTokenAT.doInBackground(ExchangeTokenActivity.java:79)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at com.example.miguel.myapplication.activity.asynctask.ExchangeTokenActivity$ExchangeTokenAT.doInBackground(ExchangeTokenActivity.java:52)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-20 20:12:40.435    2559-2577/com.example.miguel.myapplication W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-20 20:12:40.440    2559-2577/com.example.miguel.myapplication W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
04-20 20:12:40.667    2559-2559/com.example.miguel.myapplication D/nattu﹕ nattunull
04-20 20:12:40.667    2559-2559/com.example.miguel.myapplication D/AndroidRuntime﹕ Shutting down VM
04-20 20:12:40.668    2559-2559/com.example.miguel.myapplication E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.miguel.myapplication, PID: 2559
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
            at com.example.miguel.myapplication.activity.asynctask.ExchangeTokenActivity$ExchangeTokenAT.onPostExecute(ExchangeTokenActivity.java:98)
            at com.example.miguel.myapplication.activity.asynctask.ExchangeTokenActivity$ExchangeTokenAT.onPostExecute(ExchangeTokenActivity.java:52)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by mgarmuno** [comment]
Hello, please just use production server if it is working well.

**Comment by natarajnattu** [comment]
We haven't test in production we are testing using test credentials ... kindly check the error once it would be very helpful

**Comment by ClemensLode** [comment]
Have you also changed the target server to test-cloud.vitadock.com?

**Comment by natarajnattu** [comment]
```
public static final String EXTERNAL_AUTH_URL  = "test-cloud.vitadock.com/auth";
public static final String EXTERNAL_LOGIN_URL = "test-cloud.vitadock.com";
public static final String EXTERNAL_DATA_URL   = "test-cloud.vitadock.com/data";
```

in    ExchangeToken.java

authorization = AuthorizationBuilder
                    .createUnauthorizedAccessRequestAuthorizationHeader(
                            uriDeviceRequest, ConstantsStorage.TEST_APPLICATION_TOKEN,
                            ConstantsStorage.TEST_APPLICATION_SECRET);

these changes are done.. pl tell me if anything i missed.
